AllCops:
  TargetRubyVersion: 2.5
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
  Exclude:
    - vendor/**/*
    - db/migrations/**/*

  DisplayCopNames:
    Enabled: true

  DisplayStyleGuide:
    Enabled: true

Naming/FileName:
  Exclude:
    - '**/Guardfile'

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 180
